name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 'node'
          cache: 'yarn'
      - name: install
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
      - name: coverage
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
